os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
    - ARCH=x86_64 DISTRIB=debian
    - ARCH=x86_64 DISTRIB=alpine
    - ARCH=armhf DISTRIB=debian
    - ARCH=armhf DISTRIB=alpine
  global:
  - secure: 1gESy/2ROlo8nvsFZYm83infTdI2flY6NqwHB79JTiSOpxsQkiFXGTzAx+6muQ5cnOqpY6VC7kB5V4zwxYZW/UPy5KHEvBGU02I8KxYccNigv46W3O6x6YGTK+t1nwDkl9dHATN5JvHbeQmZ1NryDZvqbaN5jWzNY56Fn6rq3e4pb8Xw6VAHCu7hKCmRWSvH4mS+kxKjjqaV4q7Vnks8iH2oqxiaeCrufrLYIXIwxboc3gEZUXDqX0zkld/qz0KUl9Cwl4tku9kfltEx3TM9gjnmn+x+EtRVxhHdtXU0/5pdRANcewZTrQqTpkJBsQIqQBaqCbCM7HZUcfXjStmoLv3mJE83HfbLovNPRkmQKgPunlxXwyDk7RvlZTCfcGlWABAhc9ziRSUZ0evMfJKlvR00EZ8PLbupTo1Vk7PMVc1uSBFCQ2dKHIyYByrcniyLtjlmYypFLQlqueQZXdWnlnSE/QkXu3xrwlw+OEIuSGzK9Q+heAQdqJpKxjjg+UTEs8+MFQaiDxzNBPK0/63Gc3RJ4NPaQJl9pcXcYhT6LhJvmuRq3ZDVWuZlYBziamMPxjvlL3aybtiVQ2qzQshg7XSbNbz7m7n6NB+43Wb6JXN5zFR07Q7EXsnsiHDVasxm/Qs4C8rZEzqyegtIpEncq/6D6fw1bA3GH5zyZPUVHmQ=
  - secure: Ie5ZiQ/ahzW6Dlk73G7QcmkNVvfP7PjJvir21OLj9553XKaYpDYOSLIXZrIyF0oVvIvirWeZ/N++ocT1ur3Z/APOI1zQ1lhXU4g+y0g48B+K62DlRWkG4rZfawEzfjZMnVGA5Mk+Ap7MUGG6Q5mQhouQp2z6DziNlhQkdJFYPQSaYYAYhjOyeP7J+vJXAUVXvlb7efGs1w7asvLPgyUEzOaStwxACtrEU0HWqel5lUGTHARJ/GQfzUyK740GOzILoKKlU9jRsoXHFgZJpjd5ytEsHMnuWq9dv3GWW1uHMlwZsf+heHXbGVdSWSFNNgZeOMHYhUSMlXaxCIEcMR72jil/BVKm8Ohem4K3Mgq2u/HmBH7IRJirEuHXzmGvPDKhdy2gnMoeqaqH1YGH/TjQ4BM9mZiZwe4MxqvFw6DeO9sXsMUkvslrB935MuSdhYgOsPPHafj3aRsVqpQVLfELmO1Zby5zCng1U3LNbtaHHX23DXBaZBqfoEBCuZEAG9ARjAc+8ZuTuuVV8ajKsEQeIUSoFDGSuftQjGnT/zCBk7rFG5OhK9eFXfmGoAVT41g03YqDr/0TeQBULtFi5okBxUBDVxPNsQkll0HRwPXGAPWL0jQfVggr4s3goHe6EhilYNyt+ejs2wH+gh10WowfRv2ievAprp46u0zGGgayqJ4=
  - secure: JDMPlcskUYimMpyCO/alQ4nS5ypzQLuJ9H4P3PaDCTym3Sumgcgh/SH509UzGY0l4eZogwcEKEK9Xq7yuLlcUyXRvXDn4HN6Kwon74DzhfRwF7lmxO8uo10tmq7AKiI+ZWzr6Qh8R3n1ISBC9SL536vnnN1tmdppJKptWxbzg/jwM8RHTiDmS2z9iXG2eYRnGQBUU3GbsAjgy+7aNDJcHYNuUID1VZm6Yk0bpxCPhDlpCAzBp1SjE6HEIV+F5oCvHxlequubBzzI+Xb7UJGBp4vOH7V2MLwatLF1O5T8/iAlj73vl5v4hLbz3SUNVU1IcfVe3NcdQTpSdH3etvcCsXJyejnXR5NatJiRhcsIw25Vken3aLRvnFeOFN2xScX4s29eXRLqXIA48NWPt43b2cC4Y6ZRVXCLjt76QJZB347FNK2A3r6btgIPuLq9jOWOaJBjQailrATor/7/r1m5N6qxkvvl1+RjCKSCnxIx2BC7uLfA7vKI8DYP0Pfk9J7qDtAYAvN8fVNluQnC1ksvgs+Vce2z3wkUP4Rv7oGSly7vn/dkLklfX8GcaPNZudNadtWFJEgxRVCdw3XhWKKY9EFwdfS6vwTG44U01gXikYx8PAOhE+3TMkbqAwM5iCIEAeUArv2t2bNAQgLhYue9ZWLrjSlBCdFFZj49WBADSkY=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} DISTRIB=${DISTRIB} build 
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} DISTRIB=${DISTRIB} push
after_script:
- docker logout
- make clean
